### ISSUE TITLE
Question: RserveCLI - Passing in R functions from C# to R

### ISSUE THREAD

**Issue by crazednuttyboy** [SurajGupta/RserveCLI2#23]
Hi Suraj,

I am trying to use your code it in an attempt to send functions to the R console within my virtual server. I can do simple and basic arithmetic as well call 1 or 2 of the built in functions i.e. getwd().

I want to try and create an R functions like "add2Nums <- function(x,y) {x+y}" from the c# side to run within R.

I was wondering if you have any kind of tutorial for a newbs like my self in how to go and use this RserveCLI code better

Thanks

**Comment by buddalasunil999** [comment]
Hi, Could you please tell me how you're evaluating functions. I'm trying to read complex functions from a file which has comments and stuff. It's failing, on top of it I am not able to get exact R error using RConnection. Your help is highly appreciated.
