### ISSUE TITLE
Consider Signing / Strongly Naming the Assembly

### ISSUE THREAD

**Issue by paulwilcox** [SurajGupta/RserveCLI2#45]
I'm referencing RserveCLI2 in an assembly that I need to sign and load into my GAC.  I notice that at least the version of RserveCLI2 that I have (mine is in folder RserveCLI2.1.0.21.0) is not signed, and so my referencing assembly can't be signed.  This can be worked around but I understand it's better practice to request that the original developers sign it.  I'm very new to Rserve, RserveCLI2, and to having to sign and load assemblies into the GAC, so please let me know if there's a better solution.  Also very new to GitHub, so please let me know if there's a better way to mentioning the problem.

**Comment by SurajGupta** [comment]
Unfortunately I no longer have time to dedicate to this project, but happy to accept a pull request.

**Comment by atifaziz** [comment]
@SurajGupta Even more reason to give some thought to the issue so lovingly numbered #42. :smile:

**Comment by SurajGupta** [comment]
lets do it - can you setup the org?

**Comment by SurajGupta** [comment]
also, do you still want to use my appveyor account or create a free one?

**Comment by paulwilcox** [comment]
I'll hold off on a pull request until the org is set up, which seems to be the direction this is going.
