### ISSUE TITLE
How to compile RserveCLI2 with SharpDevelop 4/5

### ISSUE THREAD

**Issue by kmlxk** [SurajGupta/RserveCLI2#46]
I tried to compile RserveCLI2 using SharpDevelop 5.1 RC / 4.3 , but it seemed that NET Framework compiler didn't understand the following line :
```

        internal static void NotifyUnhandledException(this Task task) =>
            OnUnhandledException(new UnhandledTaskExceptionEventArgs(task));

```

**Comment by SurajGupta** [comment]
sorry, I don't have experience with SharpDevelop.  And I'm no longer maintaining this repo.  Maybe someone else can help?

**Comment by atifaziz** [comment]
@kmlxk That line is in C# 6 syntax (specifically expression bodied function member). I don't have experience with SharpDevelop either but I would check which version supports C# 6 or how to configure it to do so.
