### ISSUE TITLE
Catching R Graphics Window

### ISSUE THREAD

**Issue by dmenne** [SurajGupta/RserveCLI2#5]
Hi, Suraj, good to know that someone is continuing work on RserveCLI. I am using RDotnet, but I believe that the combination with RServe is the better choice in the long run, because the people behind Rserve are a well-established team, while RDotnet is virtually abandoned.

My main reason for still working with RDotnet is graphics; I have managed to capture the R-Graphics file, and have all features of it available, e.g. using the right mouse button to save the plot in different formats. 

See http://rdotnet.codeplex.com/workitem/7 for the code.

Because of these features, I much prefer this method to the alternative of generating a png file, and import it; I found some Java code floating around doing it that way.

However, as I see there is nothing stopping us from using the hook-code I used for RDotnet for RServe. I am currently working on projects with higher priority, but if you want to give it a try...

Dieter

**Comment by SurajGupta** [comment]
closing out - can be re-opened as needed.
